### ISSUE TITLE
Jekyll source code

### ISSUE THREAD

**Issue by robinmetral** [sylvaindurand/sylvaindurand.org#1]
Hi Sylvain,
I love your site and how you've tweaked Jekyll with a focus on web (French) typography!

On your about page, you're mentioning the source code is open source. I see your markdown files in this repo, but not `_includes`, `_layouts`, `_sass`, and so on. I'd love to be able to access it to get inspiration for my own Jekyll sites!

Is this something you're planning on doing?
Bonne journée :)

**Comment by sylvaindurand** [comment]
You're right, the website used to be completely open source, but some people started to fork it and change it for their own work, despite the license.

Then, Google started to put forks hosted on GitHub page, which were not updated, higher in search results... 

That's why I decided to put only the posts on Github, in order to allow people comment/. I'll give the code to anyone ask me to: I'm going to update the "About" section about it!

**Comment by robinmetral** [comment]
Thanks for clarifying, I understand!

It's too bad that this kind of licence infringement discourages people to release their code :slightly_frowning_face: 

Anyway, I'll get in touch if I want to see your source to get inspiration for my own Jekyll site - I particularly like your multilingual features (I've seen the repo) and the styling of your side notes + code snippets.

Bonne continuation!
